### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by jakew1ll** [SolderedElectronics/Workhours-Device-Inkplate6#1]
The readme is very devoid of information. I may be a dumb, but I am looking to incorporate some of the tact that this project took. Although, while I learn more about programming for these architectures. Is there any more links or information about this project? For example: Does it require additional hardware beyond the inkplate6plus ?

**Comment by rsoric** [comment]
Hi @jakew1ll , this is an internal project for which we just happened to make the repository public. It's a device which uses a RFID tag reader and stores employee in-office time data to an SD card. The information is also available by accessing the ESP32 via a local IP if you're connected to the same network.

If you want to learn more about ESP32 based projects, check out this smart watch project which we recently published: https://github.com/SolderedElectronics/Soldered-Smart-Watch
